ekf_filter_node:
    ros__parameters:
        frequency: 50.0
        two_d_mode: false
        publish_tf: true

        map_frame: map
        odom_frame: odom
        base_link_frame: base_footprint
        world_frame: odom

        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az
        odom0: odometry/unfiltered
        odom0_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, false,
                       false, false, false]

        #imu0: imu/accel_gyro
        #imu0_config: [false, false, false,
        #              false, false, false,
        #              false, false, false,
        #              true, true, true,
        #              true, true, true]

        # Устранение гравитации, true - устранения нет
        #imu0_remove_gravitational_acceleration: true

        imu0: imu/orientation
        imu0_config: [false, false, false,
                      true, true, true,
                      false, false, false,
                      false, false, false,
                      false, false, false]